2019.08.29 News GET & POST 기능 1차 구현. USER app 작성시,  Comment 기능 구현 예정.
wecode-bootcamp-korea/woori-doori-backend pull request #2
Opened 2019-08-29 14:24 UTC by CHOISEUNGYOUN

2019-08-30 03:26 UTC, ulfrid commented on news/models.py
> +		db_table = 'title'
class=News인데 

테이블명은 title인게 이상하네요. 확인 부탁드립니다.

2019-08-31 09:55 UTC, rampart81 commented on WooriDooriBackEnd/settings.py
> +#    'django.contrib.admin',
지워주세요

2019-08-31 10:17 UTC, rampart81 requested changes

2019-08-31 10:17 UTC, rampart81 commented on WooriDooriBackEnd/settings.py
> +#    'django.contrib.admin',
지워주세요

2019-08-31 10:17 UTC, rampart81 commented on news/models.py
> +
불필요한 빈칸 지워주세요

2019-08-31 10:17 UTC, rampart81 commented on news/models.py
> +	updated_at = models.DateField(auto_now = True)
`updated_at` 은 필요하지 않은거 같아요

2019-08-31 10:17 UTC, rampart81 commented on news/models.py
> +		db_table = 'tag'
`tag` ==> `tags`

2019-08-31 10:17 UTC, rampart81 commented on news/views.py
> +
불필요한 빈칸 줄여주세요

2019-08-31 10:17 UTC, rampart81 commented on news/views.py
> +
불필요한 빈칸은 줄여주세요. 빈칸은 한칸 이상 하지 않습니다.

2019-08-31 10:17 UTC, rampart81 commented on news/views.py
> +            return JsonResponse({'message': 'the tag you tried already exists!'}, safe=False, status=405)
`messsage`는 프론트엔드가 비교해서 사용한다면 비교가 더 쉬운 포멧으로 바꿔주세요

2019-08-31 10:17 UTC, rampart81 commented on news/views.py
> +        tag_data = list(Tag.objects.values())
`list(Tag.objects.values()` ==> `Tag.objects.values()` 로 가능할거 같은데 확인 해보세요

2019-08-31 10:17 UTC, rampart81 commented on news/views.py
> +        tag_data = list(Tag.objects.values())
`tag_data = list(Tag.objects.values())`

==>

```
tag_data = [{
    "id" : tag.id, 
    "tag" : tag.tag
} for tag in Tag.objects.values()]

tag_data = [ ]
for tag in Tag.objects.values()
    tag_data.append({"id": tag.id, "tag" : tag.tag})
```

2019-08-31 10:17 UTC, rampart81 commented on news/views.py
> +            return JsonResponse({'message': 'the tag you tried already exists!'}, safe=False, status=405)
`status =405` ==> `stutus=409`

2019-08-31 10:17 UTC, rampart81 commented on news/views.py
> +        except:
```
except KeyError as err:
    return JsonResponse({'message': 'TAG_MISSING'}, safe=False, status=400)
except IntegrityError  as err:
    return JsonResponse({'message': 'the tag you tried already exists!'}, safe=False, status=405)
```

2019-08-31 10:17 UTC, rampart81 commented on news/views.py
> +        result = []
빈칸 넣어주세요

2019-08-31 10:17 UTC, rampart81 commented on news/views.py
> +                          })
list comprehension 으로 바꿔주세요

2019-08-31 10:17 UTC, rampart81 commented on news/views.py
> +        for delta in news_data:
`delta` ==> `data`

2019-08-31 10:17 UTC, rampart81 commented on news/views.py
> +                            'tag'       : Tag.objects.get(pk = delta['tag_id']).tag,
```
                            'tag_id'    : Tag.objects.get(pk = delta['tag_id']).id,
                            'tag'       : Tag.objects.get(pk = delta['tag_id']).tag,
```

===>

tag = Tag.objects.get(pk = delta['tag_id'])
...
`tag_id`: tag.id,
'tag' : tag.tag

2019-08-31 10:17 UTC, rampart81 commented on news/views.py
> +                          })
Pagination 넣어주세요:
아래 참조하세요
```
Fetch specific number of rows
SELECT *
FROM Person
LIMIT 10;
Person.objects.all()[:10]
LIMIT AND OFFSET keywords
SELECT *
FROM Person
OFFSET 5
LIMIT 5;
Person.objects.all()[5:10]
```

2019-08-31 10:17 UTC, rampart81 commented on news/views.py
> +                          })
JOIN 으로 읽으셔서 필요한 필드를 한번에 다 읽어주세요. 

`select_related` 참조 하세요

2019-08-31 10:17 UTC, rampart81 commented on news/views.py
> +            new_tag = Tag.objects.get(pk = data['tag'])
`pk = data['tag']` ==> `pk = data["tag_id"]`

2019-09-02 10:45 UTC, rampart81 requested changes

2019-09-02 10:45 UTC, rampart81 commented on news/models.py
> +
불필요한 빈칸 삭제해주세요

2019-09-06 10:15 UTC, rampart81 requested changes

2019-09-06 10:15 UTC, rampart81 commented on news/urls.py
> +    path('/<int:tag_nums>/<int:nums>',NewsView.as_view()),
query string 써주세요

`news?offset=0&limit=10`

2019-09-06 10:15 UTC, rampart81 commented on news/views.py
> +		          } for data in raw_data][nums*10:nums*10+10]
프론트엔드가 정하게 해주세요

2019-09-06 10:15 UTC, rampart81 commented on comments/views.py
> +class CommentsView(View):
이 파일 빼주세요

2019-09-07 14:00 UTC, merged