view.py
wecode-bootcamp-korea/woori-doori-backend pull request #5
Opened 2019-09-04 13:20 UTC by bmh8993

칼럼명 변경에 따른 수정
    구글 소셜 로그인 추가

2019-09-06 10:10 UTC, rampart81 requested changes

2019-09-06 10:10 UTC, rampart81 commented on users/views.py
>  from WooriDooriBackEnd import settings
`import settings`

2019-09-06 10:10 UTC, rampart81 commented on users/views.py
>  import pdb
`pdb`

2019-09-06 10:10 UTC, rampart81 commented on users/views.py
>          except ObjectDoesNotExist:
`ObjectDoesNotExist` ==> `User.NotExist`

2019-09-06 10:10 UTC, rampart81 commented on users/views.py
> +
빈줄은 하나만

2019-09-06 10:10 UTC, rampart81 commented on users/views.py
> +                'exp': datetime.datetime.now() + datetime.timedelta(seconds = 60 * 60 * 24),
`ONE_DAY = 60 * 60 * 24`

`datetime.timedelta(seconds = ONE_DAY)`

2019-09-06 10:10 UTC, rampart81 commented on users/views.py
> +
빈칸 지워주세요

2019-09-06 10:10 UTC, rampart81 commented on users/views.py
>  from WooriDooriBackEnd import settings
`WooriDooriBackEnd` ==> `woori-doori-api`

2019-09-06 10:10 UTC, rampart81 commented on users/urls.py
> +    path('/google', GoogleAuthView.as_view()),
`/google-auth`

2019-09-07 03:03 UTC, bmh8993 commented on users/views.py
>  from WooriDooriBackEnd import settings
위와 같이 수정하니 settings가 없다고 확인됩니다

2019-09-08 06:57 UTC, closed without merging