Recipe관련 API구현
wecode-bootcamp-korea/woori-doori-backend pull request #6
Opened 2019-09-04 14:31 UTC by hkhch

1. Category Get함수 구현
1.1 End Point : Get IP:8000/recipe/category

2. Recipe Get함수 구현
2.1 End Point: Get IP:8000/recipe/recipes
 : Body에 Command Type과 전달인자를 전달하여 명령유형을 분류
	- command : Recipe Get명령의 유형 결정 
           (1 : 해당 Recipe의 Detail정보 전송, 2: Category별 Recipe정보 전송, 3: 최신 Recipe정보 전송)
	- recipe_no: Recipe 번호 (command_1에 필요한 인자)
	- categoryItem_no : 찾을 Category Item 번호 (command_2, 3에 필요한 인자)
	- start_no : 찾을 Recipe의 시작 번호 (페이지 전환시 개수 가변적으로 호출하기 위해 필요)
	- recipe_cnt : 희망하는 Recipe 수량 (찾은 값이 작은 경우 찾은 Recipe전송)

cf. Test를 위해 Django shell에서 호출할 initDBForTest()함수 구현 (추후 삭제 예정)

2019-09-05 11:52 UTC, devops-andrew requested changes

2019-09-05 11:52 UTC, ulfrid commented on recipe/models.py
> +    category_no = models.IntegerField()
category_no => category_number 가 좋을것 같습니다.
Primary Key  id 외에 별도로 관리하는 넘버의 존재이유도 알고 싶습니다.

2019-09-05 11:52 UTC, ulfrid commented on recipe/models.py
> +    item_no = models.IntegerField()
여기도 마찬가지입니다. item_no => item_number

2019-09-05 11:52 UTC, ulfrid commented on recipe/models.py
> +    recipe_no = models.IntegerField()
여기도요 recupe_no  => recipe_number

2019-09-05 11:52 UTC, ulfrid commented on recipe/views.py
> +
의도는 알겠지만 불필요한것 같습니다. 해당 리턴에 기술하면 되고, 리턴 메세지 또한 
```
"DOES_NOT_EXIST": "데이터가 존재하지 않습니다."  
==>  {"message":"DATA_NOT_FOUND"}
``` 
가 좋을것 같습니다.

2019-09-05 11:52 UTC, ulfrid commented on recipe/views.py
> +            return JsonResponse(RETURN_MESSAGE["DOES_NOT_EXIST"], safe=False, status=204)
DATA_NOT_FOUND라면 status=404가 맞습니다.
return message가 바뀐다면 safe=false가 필요없습니다.

2019-09-05 11:52 UTC, ulfrid commented on recipe/views.py
> +        # pdb.set_trace()
디버거는 마스터 코드에 주석도 포함시키지 않아야 합니다.

2019-09-05 11:52 UTC, ulfrid commented on recipe/views.py
> +import ipdb as pdb
디버거는 뺴주셔야 합니다.

2019-09-05 11:52 UTC, ulfrid commented on recipe/views.py
> +                categoryItemIndex = categoryItemIndex + 1
테스트코드는 마스터로 통합되지 않도록 사전에 제거해주세요#1

2019-09-05 11:52 UTC, ulfrid commented on recipe/views.py
> +                return HttpResponse(status=400)
불필요한 리턴같습니다.

2019-09-05 11:52 UTC, ulfrid commented on recipe/views.py
> +            return JsonResponse(result, safe=False, status=200)
리스트 형태로 반환되는 데이터라 할지라도, 
{"result":result}로 하시면 safe=False를 사용하지 않으셔도 됩니다.

2019-09-05 11:52 UTC, ulfrid commented on recipe/views.py
> +
테스트코드는 마스터로 통합되지 않도록 사전에 제거해주세요#2

2019-09-05 11:52 UTC, ulfrid commented on recipe/views.py
> +        # pdb.set_trace()
pdb제거부탁드립니다~

2019-09-06 10:03 UTC, rampart81 requested changes

2019-09-06 10:03 UTC, rampart81 commented on recipe/models.py
> +
빈칸 한줄 이상은 안넣습니다.

2019-09-06 10:03 UTC, rampart81 commented on recipe/models.py
> +        return self.category_no
디버깅용이면 삭제해주세요.

2019-09-06 10:03 UTC, rampart81 commented on recipe/models.py
> +        return self.item_no
이것도 마찬가지로 지워주세요.

2019-09-06 10:03 UTC, rampart81 commented on recipe/models.py
> +    categoryItem = models.ForeignKey(CategoryItem, on_delete=models.CASCADE)
`categoryItem` ==> `category_item`

2019-09-06 10:03 UTC, rampart81 commented on recipe/views.py
> +
빈칸 1개로 줄여주세요

2019-09-06 10:03 UTC, rampart81 commented on recipe/views.py
> +    def initDBForTest():
`initDBForTest` ==> `init_db_for_test`

2019-09-06 10:03 UTC, rampart81 commented on recipe/views.py
> +            return JsonResponse(result, safe=False, status=200)
```
{
    "data": [
       ...
    ],
   "total_count": 100
}
```

2019-09-06 10:03 UTC, rampart81 commented on recipe/views.py
> +            return JsonResponse(result, safe=False, status=200)
참고용:

```
In [11]: def test1():
    ...:     return 1
    ...:
In [11]: def test1():
    ...:     return 1
    ...:

In [12]: def test2():
    ...:     return 2
    ...:

In [13]: switch = {
    ...:     "1" : test1,
    ...:     "2" : test2
    ...:
    ...: }

In [14]:

In [14]: switch["1"]()
Out[14]: 1

In [15]: switch["2"]()
Out[15]: 2
```

2019-09-07 15:57 UTC, merged